hash-define-organization/Hacktober-Fest-2021

MobileDev/Kotlin/ROADMAP.md

added roadmap for android dev kotlin

---

WebDev/Backend/Directory-Explorer/index.js
WebDev/Backend/Directory-Explorer/package.json

Added the building blocks for the file directory code. Please review.

Added the basic code for the script

---

DSA/Cpp/Linked_List.cpp

Added singly linked list program in C++. 
Please review and provide feedback.
Resolve issue #9 
Thank you!

Added singly Linked list in Cpp

---

DSA/Cpp/reverseSinglyLinkedList.cpp

Leetcode problem # 206 added in DSA/Cpp/ folder

Created reverseSinglyLinkedList.cpp

---

DSA/Python/Stopwatch

A python program to run timer as per user enter the value in seconds.

Stopwatch using python

---

DSA/Cpp/Group Anagrams.cpp

Added Group Anagrams solution of leetcode problem 49

Added Group Anagram solution (Leetcode Problem 49)

---

WebDev/HTML-CSS/To Do List/README.md
WebDev/HTML-CSS/To Do List/list app.js
WebDev/HTML-CSS/To Do List/list style.css
WebDev/HTML-CSS/To Do List/sample.html

html, css, js, .md files included. This is a VanillaJS project (not using any frameworks).

Added To Do List code

---

DSA/Cpp/2_d_Spiral_matrix_problem.cpp

closes #35 
Signed-off-by: Harshal <harshalrathore2014@gmail.com>

added 2-D Matrix Spiral Problem

---

DSA/Cpp/reverse_integer.cpp

Completed reverse integer(DSA) #33

---

Other/Url-Shortner/app.py
Other/Url-Shortner/static/css/main.css
Other/Url-Shortner/static/js/main.js
Other/Url-Shortner/templates/index.html
Other/Url-Shortner/urls.csv

- written in python
- used flask framework
- stores past URLs and their codes
- easy to deploy

Url shortner/python

---

DSA/Java/Dynamic_Programming/Stock Buy Sell Problem/Problem Statement
DSA/Java/Dynamic_Programming/Stock Buy Sell Problem/Solution.java

Resolving Issue - [Stock Buy Sell Problem #74 ](https://github.com/hash-define-organization/Hacktober-Fest-2021/issues/74)
Added 2 files in DSA/Java/Dynamic Programming
Stock Buy Sell Problem Statement
Stock Buy Sell Solution.java

Stock buy sell problem

---

DSA/Java/Sorting algorithms/CyclicSort.java
DSA/Java/Sorting algorithms/InsertionSort.java
DSA/Java/Sorting algorithms/SelectionSort.java
DSA/Java/Sorting algorithms/bubbleSort.java

This PR resolves issue #51 
I've added bubble, insertion, selection and cyclic sorting algorithms in DSA/JAVA/Sorting algorithms.

Added sorting algorithms in DSA/JAVA/ 

---

DSA/Cpp/Dynamic_Programming/Maximum square area in Binary Matrix.cpp

Code added for issue #47 . Please let me know if you require any change.

Code added for issue 47

---

WebDev/HTML-CSS/SurveyForm/survey.css
WebDev/HTML-CSS/SurveyForm/surveyForm.html

Created a survey form and attached required screenshots. Please consider my PR.
Issue - #152

Added survey form 

---

ML-AI/Spam and Ham detection Model/Spam and Ham Detection.ipynb
ML-AI/Spam and Ham detection Model/smsspamcollection/SMSSpamCollection
ML-AI/Spam and Ham detection Model/smsspamcollection/readme

Added Spam/Ham detection Model under issue #163

Spam Ham detection Model

---

Computer Networks/ByteStuffing.cpp
Computer Networks/CRC.cpp
Computer Networks/DistanceVectorRoutingProtocol.cpp
Computer Networks/LRC.cpp
Computer Networks/OSI_Model.cpp
OS Concept/OS/FirstComeFirstServe.cpp
OS Concept/OS/NonPremetiveScheduling.cpp
OS Concept/OS/NonPremetiveShortestJobFirst.cpp
OS Concept/OS/PremetiveShortestJobFirst.cpp
OS Concept/OS/PriorityPremetiveScheduling.cpp
OS Concept/OS/RoundRobinScheduling.cpp

Pls consider my PR for the issue #138 . 
This folder contain problems like 
1. OSI model using graphics , when you run this program a running graphics will displayed on screen which show how the data transfer takes place between the nodes of OSI.
Rest problems are based on error correction and detection simply in cpp
2. CRC
3. Distance vector routing protocol
4. LRC
5. Bytestuffing

Computer Networking Problems/ Algo

---

OS Concept/OS/FirstComeFirstServe.cpp
OS Concept/OS/NonPremetiveScheduling.cpp
OS Concept/OS/NonPremetiveShortestJobFirst.cpp
OS Concept/OS/PremetiveShortestJobFirst.cpp
OS Concept/OS/PriorityPremetiveScheduling.cpp
OS Concept/OS/RoundRobinScheduling.cpp

Pls consider my PR for issue #136 .
These are some CPU scheduling Algorithsm coded in cpp using graphics.
1. First come first serve
2. Premetive shortes job first
3. Non Premetive shortes job first
4. Priority premetive scheduling
5. Round Robin scheduling
6. Non Premetive scheduling
Round Robin
Priority premetive scheduling
Premetive shortes job first
Non Premetive scheduling
Non Premetive shortes job first
First come first serve

OS concept

---

DSA/Cpp/Sorting-Algorithms/Bubble-Sort.txt
DSA/Cpp/Sorting-Algorithms/Insertion-Sort.txt
DSA/Cpp/Sorting-Algorithms/Selection-Sort.txt

I have added sorting algorithms 
1)selection sort
2)merge sort
3)bubble sort
please review!

sorting algorithms

---

DSA/Cpp/n_C_r_mod_P.cpp

please review my PR and let me know if it needs any change. Thankyou

added nCr mod (1e9+7) code in DSA/CPP

---

Program to Check whether the sentence is pangram

Basically pangram is a sentence containing all the letters in the English alphabet!

Program to Check whether the sentence is pangram #53

---

ML-AI/Similar and odd word model/word2vec model.ipynb

Added the model stated in issue #208

Added ML Model to find odd and similar words

---

DSA/Python/Reverse an integer

A python program to reverse input integer.

Reverse a number

---

Gtkmm-Codes-CPP/CheckButton/checkButton.cpp
Gtkmm-Codes-CPP/CheckButton/checkButton.h
Gtkmm-Codes-CPP/Introductory101/hello-world-gtk.c
Gtkmm-Codes-CPP/Introductory101/hello.c
Gtkmm-Codes-CPP/Introductory101/packing.c
Gtkmm-Codes-CPP/Introductory101/simple.cc
Gtkmm-Codes-CPP/Introductory101/testing.cpp
Gtkmm-Codes-CPP/button/button.cpp
Gtkmm-Codes-CPP/button/button.h

I've added few of the basic Gtkmm codes. These codes are tried and tested. I've also done proper commenting in my code so that it will be easier for beginners to understand.

Added basic codes for Gtkmm

---

CyberSec/Anti-arp system.py

I have added a python file that contains a code to detect, prevent and recover from man in the middle attacks in LAN network.
Kindly approve my PR and add hacktoberfest-accepted tag.

Detect, prevent and recover MITM attacks

---

DSA/Others/Heaps/minHeap.go
DSA/Others/Linked_List/doublyLinkedList.go
DSA/Others/Linked_List/singlyLinkedList.go
DSA/Others/Queues/queue.go
DSA/Others/Stacks/stack.go
DSA/Others/Trees/binary_tree.go
DSA/Others/Trees/bst.go

Implemented all the major Data structures in GOLANG.
```
DSA/Others/Heaps/minHeap.go
DSA/Others/Linked_List/doublyLinkedList.go
DSA/Others/Linked_List/singlyLinkedList.go
DSA/Others/Queues/queue.go
DSA/Others/Stacks/stack.go
DSA/Others/Trees/binary_tree.go
DSA/Others/Trees/bst.go
```
credits:- most helpful explanation you can find on **Abdul Bari**'s youtube channel.

DSA_GOLANG
